### ISSUE TITLE
overall left & right "page boundary" appear uneven & unequal between floats & flex

### ISSUE THREAD

**Issue by 0iseaux** [0iseaux/Sweet-eats#4]
https://0iseaux.github.io/hyf-html-css/

**Comment by ChristerNilsson** [comment]
Link above does not work.

**Comment by 0iseaux** [comment]
ooops! forgot to update this after updating the gh page. updated above.

**Comment by ChristerNilsson** [comment]
Please take a screen dump and draw some arrows to indicate what you would like to change!
I'm really bad at design myself, so please guide me.
Also, I don't know which parts are using floats or flex.

**Comment by 0iseaux** [comment]
[The problem as it appears]

[Re overall left & right "page boundary" appear uneven & unequal between floats & flex (#4).pdf](https://github.com/0iseaux/hyf-html-css/files/3201355/Re.overall.left.right.page.boundary.appear.uneven.unequal.between.floats.flex.4.pdf)

The annotated screenshot shows the "alignment" discrepancy in terms of space between and margin around the items (hope it is clear).

I wonder if such differences have got to do with the CSS code or if they are the inherent (inevitable?) between using floats and flexboxes in grids.

[Looking at the code]

I believe I have applied common settings to both float & grid items <li>, their containers <ul> and child items (<h3>, <img> <p>), such as padding, margin, border, etc (lines 45-80, 92-98)

The only apparent differences/divergent settings are:
- for float items (#grid-floats>.grid-item) (lines 82-83)
- for flex items (#grid-flex>.grid-item) (lines 85-90):
    flex: 1 1 auto;
    justify-content: space-around;
    align-content: space-around;

I have tried out with the inspector which seemed to show that these settings to the flex items only alter the alignment of the contents, not of the flex items themselves.

**Comment by ChristerNilsson** [comment]
Eventually this problem can be solved by tweaking the widths, paddings, and margins for floats and flexboxes. It is important to have a mental graph of how they add up to 100%. Like padding + width + padding and so on for different devices.

I have added the background colors red,green and blue to make it clear which device we are looking at.

One outstanding problem I have is the text "Grid with flexbox". I don't know how to move it without touching the .html file. Before doing "clear: both" I had the same problem with the boxes sneking in to  the upper right corner.

**Comment by ChristerNilsson** [comment]
Sass makes the style more pythonic. Using tabs instead of {}.
But, it is also possible to calculate numbers.
Might be nice for all these widths.
https://github.com/ChristerNilsson/vscode-foo/blob/master/HTML-CSS/Week2/style.sass

**Comment by 0iseaux** [comment]
Sass seems handy. I'm figuring out which way to install it... 

meanwhile I'm recalculating the width, padding, etc... thinking aloud here: I thought box-sizing in CSS could solve this addition problem by taking into account all of these (except margins); but maybe I am using the inappropriate units (px/em/rem/%/vw)?
```
html {
    box-sizing: border-box;
  }
  *, *:before, *:after {
    box-sizing: inherit;
  }
```

**Comment by 0iseaux** [comment]
1. `clear: both; `
> One outstanding problem I have is the text "Grid with flexbox". I don't know how to move it without touching the .html file. 

It seems applying `clear: both; `to the <h2>Grid with flexbox would push it down as well.

*** I have a few more follow-up/trivial questions and thoughts:

2. So actually one doesn't need to turn any elements into **grid containers** (and also **grid items**) to achieve the (same?) desired layout with floats and flexbox? I thought "grid with floats" and "grid with flexbox" means the placing of floats and flexboxes inside "grids"... If so, then _when_ would we really need to use grid (e.g. with flexbox)?

3. Apparent vertical "margin" imbalance still seem to exist within and between floats and flexbox, except for the floats in desktop mode: (screenshots attached). Is this due to some inherent (inevitable) differences between floats & flexboxes (hence "normal")?
![desktop_floats](https://user-images.githubusercontent.com/49612325/58168072-b4f99800-7c8d-11e9-8a7e-f2705dd9d71a.png)
![desktop_floats(above)_flexbox(below)](https://user-images.githubusercontent.com/49612325/58168076-b7f48880-7c8d-11e9-85c4-75b8ae381966.png)
![tablet_floats](https://user-images.githubusercontent.com/49612325/58168087-bd51d300-7c8d-11e9-8f4e-45f04f740c1a.png)
![tablet_floats(above)_flexbox(below)](https://user-images.githubusercontent.com/49612325/58168090-c04cc380-7c8d-11e9-974f-02eab7b0d6f4.png)
![mobile_floats](https://user-images.githubusercontent.com/49612325/58168096-c347b400-7c8d-11e9-91d5-fd76228526f3.png)
![mobile_floats(above)_flexbox(below)](https://user-images.githubusercontent.com/49612325/58168100-c5117780-7c8d-11e9-9861-bbe22a1e3fb8.png)

3. I think I know the differences between the different sizing units in CSS. e.g. px, %, em, rem, vw, etc and currently find vw most useful in making the sizing responsive to the device width.  But is there a thing called I 'overusing' vw?  

4. Can vw or flexboxes practically replace the need for media queries?  I haven't quite figured out how, for example, the code below works to achieve this:

```
.flex-container {
 display: -webkit-box;
 display: -moz-box;
 display: -ms-flexbox;
 display: -webkit-flex;
 display: flex;
```

5. media queries 
If we are to use media queries, I wonder how we should define the min- or max-device-width, given the different device size within each category (e.g. tablet)
Google told me the "standard" device widths are something like this:

> desktop: @media screen and (min-device-width: 1025px){    
> tablet: @media screen and (min-device-width: 768px) and (max-device-width: 1024px)
> mobile: @media screen and (max-device-width: 640px){

But wouldn't this pose an issue for devices with a width between 640-768px, which may revert back to the default/desktop layout in ?
