### ISSUE TITLE
week2/ looking for a more efficient way to select multiple "nth-child(n)"s  and place them in grid areas

### ISSUE THREAD

**Issue by 0iseaux** [0iseaux/Sweet-eats#5]
links: https://0iseaux.github.io/hyf-html-css/

**Comment by ChristerNilsson** [comment]
Link does not work

**Comment by ChristerNilsson** [comment]
What do you want to do more efficiently? 
Do you want to reduce the file size of html or css?
You might take a look at [Sass](https://sass-lang.com/guide)

**Comment by 0iseaux** [comment]
links url updated.

I wonder if there is a more efficient way to select multiple grid items using "(nth-child(n))", other than the convenient  "(even)" and "(odd)"  (e.g. on lines 149 & 154 of styles.css).

I find my current way of dealing with float and flex items for the **Tablet view** extremely inefficient and repetitive, in particular in:
1) selecting various float items (**lines 188-256**) and flex items (**lines 261-324**) **one by one** using **nth-child**; 
2) placing each of the float items (**lines 188-256**) and flex items (**lines 261-324**)  different grid-areas **one by one** (**lines 188-256**);  

I believe there are more efficient (smarter) ways of selecting the items or placing them into different grid-areas, but have not yet found any...
